version: 0.0
os: linux
files:
  # インスタンス上の特定の場所にコピーする、ファイルの配置場所
  - source: /
    destination: /home/ec2-user/kawasaki-restapi
    overwrite: true
permissions:
  - object: /
    owner: ec2-user
    group: ec2-user
    mode: 755
    pattern: "**"
