spring:
  datasource:
    url: jdbc:mysql://kawasakiryosuke-db.c35xcnhiknum.ap-northeast-1.rds.amazonaws.com/restfulapi
    username: rest_api_user
    password: .5~?;(oN=JJ^sKqc3c}@iN(^)dXT(p
    driverClassName: com.mysql.cj.jdbc.Driver

setting:
  frontend:
    url: https://kawasakiryosuke-front.s3.ap-northeast-1.amazonaws.com
  github:
    client: "${GITHUB_CLIENT_ID}"
    secret: "${GITHUB_CLIENT_SECRET}"
    callbackUrl: ${setting.frontend.url}/github/callback
  oauth:
    redirectUrl: ${setting.frontend.url}
  image:
    uploadDir: images/
  log:
    accessLogPath: /home/ec2-user/logs/
    datetimeFormat: "yyyy/MM/dd"