spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kawasaki_restfulapi
    username: root
    password:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
  throw-exception-if-no-handler-found: true
  resources:
  add-mappings: false
  localImagesPath: src/main/resources/static/images


