#============================================================================
# Spring設定(本番環境)
#============================================================================
spring:
  datasource:
    url: jdbc:mysql://kawasakiryosuke-db.c35xcnhiknum.ap-northeast-1.rds.amazonaws.com/kawasaki_restfulapi
    username: admin_kawasaki
    password: kawayan1111
    driverClassName: com.mysql.cj.jdbc.Driver
    database: MYSQL
#============================================================================
# アプリケーション固有設定(本番環境)
#============================================================================
setting:
  frontend:
    url: https://kawasakiryosuke-front.s3.ap-northeast-1.amazonaws.com
    allowPath: /api/**
  oauth:
    redirectUrl: ${setting.frontend.url}/token/
  github:
    client: "${GITHUB_CLIENT_ID}"
    secret: "${GITHUB_CLIENT_SECRET}"
    callbackUrl: http://ec2-18-179-4-82.ap-northeast-1.compute.amazonaws.com:8080/github/callback
  # 商品画像のアップロード先
  image:
    uploadDir: images/
  log:
    accessLogPath: /home/ec2-user/logs/
    datetimeFormat: "yyyy/MM/dd"
#============================================================================
# AWS S3 設定(本番環境)
#============================================================================
aws:
  region: ap-northeast-1
  accessKey: "${AWS_ACCESS_KEY}"
  secretKey: "${AWS_SECRET_KEY}"
  s3bucket: kawasakiryosuke-image
  imageDir: images/
