spring:
  datasource:
    url: jdbc:mysql://kawasakiryosuke-db.c35xcnhiknum.ap-northeast-1.rds.amazonaws.com/kawasaki_restfulapi
    username: admin_kawasaki
    password: kawayan1111
    driverClassName: com.mysql.cj.jdbc.Driver

setting:
  frontend:
    url: https://kawasakiryosuke.com
  github:
    client: "${GITHUB_CLIENT_ID}"
    secret: "${GITHUB_CLIENT_SECRET}"
    callbackUrl: ${setting.frontend.url}/github/callback
  oauth:
    redirectUrl: ${setting.frontend.url}
  # 商品画像のアップロード先
  image:
    uploadDir: images/
  log:
    accessLogPath: /home/ec2-user/logs/
    datetimeFormat: "yyyy/MM/dd"