#フレームワーク側の設定
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kawasaki_restfulapi
    username: root
    password:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  localImagesPath: src/main/resources/static/images
  jackson:
    #null項目は出力しない
    default-property-inclusion: non_null
    serialization:
      #整形する
      INDENT_OUTPUT: true
#アプリケーション側の設定
setting:
  github:
    client: "${CLIENT_ID}"
    secret: "${CLIENT_SECRET}"
    callbackUrl: http://localhost:8080/github/callback
  oauth:
    accessTokenSessionKey: "token"
  log:
    accessLogPath: "src/main/resources/logs/access/access."
    datetimeFormat: "yyyy/MM/dd"
