#============================================================================
# Spring設定(本番環境)
#============================================================================
spring:
  datasource:
    url: jdbc:mysql://kawasakiryosuke-db.c35xcnhiknum.ap-northeast-1.rds.amazonaws.com/kawasaki_restfulapi
    username: admin_kawasaki
    password: kawayan1111
    driverClassName: com.mysql.cj.jdbc.Driver
    database: MYSQL
#============================================================================
# アプリケーション固有設定(本番環境)
#============================================================================
setting:
  frontend:
    url: https://d3396oif6lnqlh.cloudfront.net
    allowPath: /api/**
  oauth:
    redirectUrl: ${setting.frontend.url}/token/
  github:
    client: ${GITHUB_CLIENT_ID}
    secret: ${GITHUB_CLIENT_SECRET}
    callbackUrl: https://d3396oif6lnqlh.cloudfront.net/github/callback
  # 商品画像のアップロード先
  image:
    uploadDir: images/
  log:
    accessLogPath: /home/ec2-user/logs/
    datetimeFormat: "yyyy/MM/dd"
