#============================================================================
# Spring設定
#============================================================================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kawasaki_restfulapi
    username: root
    password:

#============================================================================
# アプリケーション固有設定
#============================================================================
setting:
  frontend:
    url: http://localhost:3000
    allowPath: /api/**
  oauth:
    redirectUrl: ${setting.frontend.url}/token/
  image:
    uploadDir: src/main/resources/static/images
  log:
    accessLogPath: "src/main/resources/logs/access/access."
    datetimeFormat: "yyyy/MM/dd"
  github:
    client: "${GITHUB_CLIENT_ID}"
    secret: "${GITHUB_CLIENT_SECRET}"
    callbackUrl: http://localhost:8080/github/callback
