#============================================================================
# Spring設定
#============================================================================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kawasaki_restfulapi
    username: root
    password:
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  jackson:
    #null項目は出力しない
    default-property-inclusion: non_null
    serialization:
      #整形する
      INDENT_OUTPUT: true
  profiles:
#============================================================================
# アプリケーション固有設定
#============================================================================
setting:
  github:
    client: "${GITHUB_CLIENT_ID}"
    secret: "${GITHUB_CLIENT_SECRET}"
    callbackUrl: http://localhost:8080/github/callback
  oauth:
    accessTokenSessionKey: "token"

#============================================================================
# AWS S3 設定
#============================================================================
aws:
  region: ap-northeast-1
  accessKey: "${AWS_ACCESS_KEY}"
  secretKey: "${AWS_SECRET_KEY}"
  s3bucket: kawasakiryosuke-image
  imageDir: images/

